#!/usr/bin/env python3
"""
brownie-config.yaml -> ape-config.yaml converter (best-effort, supplemental).

Run AFTER the jssg codemod has handled Python source files. Detects
brownie-config.yaml in the target project and emits ape-config.yaml with the
known fields translated. Unknown sections are preserved as YAML comments
so the user can finish the migration manually.

Usage:
    python scripts/migrate_config.py /path/to/brownie/project

Mapping (only well-known top-level keys):
    project_structure         -> dropped (Ape uses fixed contracts/, scripts/, tests/)
    networks.default          -> default_network on the active ecosystem
    networks.<name>           -> ethereum.<name> entries (assumes ethereum)
    dependencies              -> dependencies (entries reformatted)
    compiler.solc.remappings  -> solidity.remappings
    compiler.solc.version     -> solidity.version
    wallets.from_key          -> dropped (Ape uses `ape accounts import`)

Anything else is preserved at the bottom of the new file as a commented-out
"# LEGACY:" block for manual review.

This is a thin helper, not a strict migrator. PyYAML is required.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "PyYAML is required: pip install pyyaml\n"
    )
    sys.exit(2)


HEADER = """\
# Generated by brownie-to-ape codemod (migrate_config.py)
#
# Review the TODO entries below — only well-known fields were translated.
# See https://docs.apeworx.io/ape/stable/userguides/config.html
"""


def translate(brownie_cfg: dict) -> tuple[dict, list[str]]:
    """Map known Brownie keys to Ape equivalents. Return (ape_cfg, todos)."""
    ape: dict[str, Any] = {}
    todos: list[str] = []

    # --- networks --------------------------------------------------------
    nets = brownie_cfg.get("networks") or {}
    if isinstance(nets, dict):
        if "default" in nets:
            ape.setdefault("ethereum", {})["default_network"] = nets["default"]
        for name, body in nets.items():
            if name == "default":
                continue
            if not isinstance(body, dict):
                continue
            ape.setdefault("ethereum", {}).setdefault(name, {})
            # cmd_settings.port -> custom provider config (TODO)
            if "cmd_settings" in body:
                todos.append(
                    f"networks.{name}.cmd_settings — Ape uses provider plugins (foundry / hardhat / anvil). Review manually."
                )

    # --- compiler.solc ---------------------------------------------------
    solc = (brownie_cfg.get("compiler") or {}).get("solc") or {}
    if isinstance(solc, dict):
        if "version" in solc:
            ape.setdefault("solidity", {})["version"] = solc["version"]
        if "remappings" in solc:
            ape.setdefault("solidity", {})["remappings"] = solc["remappings"]
        if "optimizer" in solc:
            ape.setdefault("solidity", {})["optimize"] = bool(
                (solc.get("optimizer") or {}).get("enabled", True)
            )

    # --- dependencies ----------------------------------------------------
    brownie_deps = brownie_cfg.get("dependencies") or []
    if isinstance(brownie_deps, list) and brownie_deps:
        # Brownie format: "smartcontractkit/chainlink-brownie-contracts@1.0.0"
        # Ape format: { name, github, version }
        ape_deps = []
        for d in brownie_deps:
            if not isinstance(d, str) or "@" not in d:
                todos.append(f"dependencies entry not parseable: {d!r}")
                continue
            slug, version = d.rsplit("@", 1)
            if "/" not in slug:
                todos.append(f"dependencies entry missing org/repo: {d!r}")
                continue
            org, name = slug.split("/", 1)
            ape_deps.append(
                {"name": name, "github": f"{org}/{name}", "version": version}
            )
        if ape_deps:
            ape["dependencies"] = ape_deps

    # --- wallets ---------------------------------------------------------
    if brownie_cfg.get("wallets"):
        todos.append(
            "wallets — Ape uses `ape accounts import <alias>` for keystores. "
            "Set up accounts via the CLI; do not commit private keys to config."
        )

    # --- dotenv ----------------------------------------------------------
    if "dotenv" in brownie_cfg:
        ape["dotenv"] = brownie_cfg["dotenv"]

    # --- catch-all -------------------------------------------------------
    HANDLED = {
        "networks", "compiler", "dependencies", "wallets",
        "dotenv", "project_structure", "reports",
    }
    leftover = {k: v for k, v in brownie_cfg.items() if k not in HANDLED}
    if leftover:
        for k in leftover:
            todos.append(f"unknown section preserved as comment: {k}")

    return ape, todos


def emit(ape_cfg: dict, todos: list[str], leftover: dict) -> str:
    out = [HEADER]
    if todos:
        out.append("# TODO(brownie-to-ape):")
        for t in todos:
            out.append(f"#   - {t}")
        out.append("")
    out.append(yaml.safe_dump(ape_cfg, sort_keys=False).rstrip())
    if leftover:
        out.append("")
        out.append("# === LEGACY: brownie-config.yaml sections without a known Ape mapping ===")
        legacy_yaml = yaml.safe_dump(leftover, sort_keys=False)
        for line in legacy_yaml.splitlines():
            out.append(f"# {line}")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.stderr.write(
            "Usage: python migrate_config.py <project-dir>\n"
        )
        return 2
    project = Path(argv[1])
    src = project / "brownie-config.yaml"
    if not src.exists():
        sys.stdout.write(
            f"No brownie-config.yaml at {src} - skipping config migration.\n"
        )
        return 0

    try:
        with src.open("r", encoding="utf-8") as f:
            brownie_cfg = yaml.safe_load(f) or {}
    except OSError as e:
        sys.stderr.write(
            f"ERROR: cannot read {src}: {e}\n"
            f"  Check file permissions and that the path resolves correctly.\n"
        )
        return 3
    except yaml.YAMLError as e:
        sys.stderr.write(
            f"ERROR: {src} contains invalid YAML: {e}\n"
            f"  Fix the syntax error in brownie-config.yaml and re-run.\n"
            f"  (No files were modified.)\n"
        )
        return 4

    if not isinstance(brownie_cfg, dict):
        sys.stderr.write(
            f"ERROR: {src} did not parse to a YAML mapping (got "
            f"{type(brownie_cfg).__name__}). Brownie configs must have "
            f"top-level keys like `networks:`, `compiler:`, etc.\n"
        )
        return 5

    try:
        ape_cfg, todos = translate(brownie_cfg)
    except Exception as e:  # noqa: BLE001 — defensive top-level catch
        sys.stderr.write(
            f"ERROR while translating config: {type(e).__name__}: {e}\n"
            f"  This is a bug - please open an issue with the brownie-config.yaml\n"
            f"  contents at https://github.com/PugarHuda/brownie-to-ape/issues\n"
        )
        return 6

    HANDLED = {
        "networks", "compiler", "dependencies", "wallets",
        "dotenv", "project_structure", "reports",
    }
    leftover = {k: v for k, v in brownie_cfg.items() if k not in HANDLED}

    out = emit(ape_cfg, todos, leftover)
    dst = project / "ape-config.yaml"
    if dst.exists():
        sys.stderr.write(
            f"WARNING: {dst} already exists - refusing to overwrite. "
            f"Wrote new content to {dst}.new instead.\n"
        )
        dst = dst.with_suffix(".yaml.new")
    try:
        dst.write_text(out, encoding="utf-8")
    except OSError as e:
        sys.stderr.write(
            f"ERROR: cannot write {dst}: {e}\n"
            f"  Check directory permissions.\n"
        )
        return 7
    sys.stdout.write(f"[OK] Wrote {dst}\n")
    if todos:
        sys.stdout.write(
            f"  ({len(todos)} TODO(s) - review the generated file before running `ape compile`)\n"
        )

    # Rename the original to .legacy so the user keeps a copy but Ape
    # doesn't accidentally pick it up.
    legacy = src.with_suffix(".yaml.legacy")
    try:
        src.rename(legacy)
    except OSError as e:
        sys.stderr.write(
            f"WARNING: wrote {dst} but could not rename {src} -> {legacy}: {e}\n"
            f"  Rename it manually so Ape doesn't pick up the legacy config.\n"
        )
        return 0
    sys.stdout.write(f"[OK] Renamed {src.name} -> {legacy.name}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
